[package]
name = "JSON-parser"
version = "0.1.0"
edition = "2021"
description = "Парсер, який реалізує граматику для JSON файлів"

[dependencies]
pest_derive = "2.7.14"
pest = "2.7.14"
anyhow = "1.0.91"
clap = "4.5.21"
thiserror = "2.0.3"
